### ISSUE TITLE
出现报错，nb被强制退出

### ISSUE THREAD

**Issue by aknyzsd** [lgc-NB2Dev/nonebot-plugin-nonememe#1]
截图如下，貌似阿里云并没有更新仓库不能通过nb安装，所以尝试下载压缩包解压安装的出现如下报错
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-nonememe/assets/121467598/4df87ad9-9e64-456e-a3e2-d4bd0c1594c4)
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-nonememe/assets/121467598/1e7aeeef-589d-4014-a730-df82d6145320)

**Comment by lgc2333** [comment]
尝试修改下面的配置项

https://github.com/lgc-NB2Dev/nonebot-plugin-nonememe/blob/master/nonebot_plugin_nonememe/config.py#L20C1-L23C6

**Comment by aknyzsd** [comment]
怎么改呢qwq

**Comment by lgc2333** [comment]
在`env` 文件修改插件配置，两种方法二选一

- 配置代理 (e.g. `nonememe_proxy=http://127.0.0.1:7890`)
- 替换成加速地址 (e.g. `nonememe_repo_prefix=https://raw.gitmirror.com/NoneMeme/NoneMeme/main`)

**Comment by aknyzsd** [comment]
问题解决，出现了新的问题
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-nonememe/assets/121467598/8b4448f4-7e76-422f-9c87-f149a0071847)
貌似是gocq的问题？

**Comment by lgc2333** [comment]
`pip install nonebot-plugin-send-anything-anywhere -U`

**Comment by aknyzsd** [comment]
问题已解决，不知为何不卸载更新总会安装0.2.4版本
卸载重装后是0.2.7
感谢
